[master]
  runner = "s3://ambiata-dispensary-v2/dist/master/master-haskell/linux/x86_64/latest/master-haskell-latest"
  version = 1

[global]
  CABAL_VERSION = "1.24.0.2"
  CACHE = "true"

[build.dist-7-10]
  GHC_VERSION = "7.10.2"

[build.dist-8-0]
  HADDOCK = "true"
  HADDOCK_S3 = "$AMBIATA_HADDOCK_MASTER"
  PUBLISH = "true"
  PUBLISH_S3 = "$AMBIATA_ARTEFACTS_MASTER"
  PUBLISH_EXECUTABLES = "master"
  GHC_VERSION = "8.0.2"

[build.branches-7-10]
  GHC_VERSION = "7.10.2"

[build.branches-8-0]
  HADDOCK = "true"
  HADDOCK_S3 = "$AMBIATA_HADDOCK_BRANCHES"
  PUBLISH = "true"
  PUBLISH_S3 = "$AMBIATA_ARTEFACTS_BRANCHES"
  PUBLISH_EXECUTABLES = "master"
  GHC_VERSION = "8.0.2"
